### PR TITLE
[LIVY-573][TESTS][THRIFT] Add tests for operation logs retrieval

### PR DESCRIPTION
**Pull request by yiheng**
## What changes were proposed in this pull request?
Add unit test for operation logs retrieval.

## How was this patch tested?
New unit tests and existing unit test

### CODE REVIEW

**Comment by jerryshao** [comment]
Please rebase the code.

**Comment by yiheng** [comment]
resolved

**Comment by mgaido91** [comment]
LGTM, may you please edit the PR title to:

```
[LIVY-573][TESTS][THRIFT] Add tests for operation logs retrieval
```

**Comment by mgaido91** [comment]
Thanks, merged to master.

**Pull request closed without merging**
