### PR TITLE
[LIVY-526] Upgrade jetty version

### PR DESCRIPTION
**Pull request by arunmahadevan**
## What changes were proposed in this pull request?

Upgrade the jetty patch version to a more recent version that has fixes for a few security issues. 

## How was this patch tested?

Existing unit tests

### CODE REVIEW

**Comment by arunmahadevan** [comment]
cc @mgaido91 @vanzin

**Comment by mgaido91** [comment]
@arunmahadevan there is a consistent UT failure. We need to address it. I think we should also have a JIRA (to be referenced here) proposing the Jetty version upgrade. Thanks.

**Comment by arunmahadevan** [comment]
@mgaido91 fixed the unit test failure and created a JIRA.

**Comment by mgaido91** [comment]
thanks. LGTM

**Comment by arunmahadevan** [comment]
thanks @mgaido91 for reviewing.

@vanzin @jerryshao , can you take it forward?

**Comment by jerryshao** [comment]
OK, LGMT. Merging to master.

**Pull request closed without merging**
