### PR TITLE
[hotfix][log] log stack trace properly

### PR DESCRIPTION
**Pull request by TisonKun**
## What changes were proposed in this pull request?

Log stack trace properly. With an automatic check pass this is the only instance.

## How was this patch tested?

straightforward

### CODE REVIEW

**Comment by TisonKun** [comment]
I can see a corresponding JIRA is necessary but given this is quite a nit change I am not sure whether we also create a dedicated JIRA. Let me know if it is expected.

**Comment by zjffdu** [comment]
LGTM, I think it is fine without creating jira ticket for this trivial change.

**Comment by TisonKun** [comment]
@zjffdu thanks for your reply. Shall we move forward?

**Comment by jerryshao** [comment]
Thanks for the fix, merging to master branch.

**Comment by TisonKun** [comment]
Thanks for your review!

**Pull request closed without merging**
