### PR TITLE
[LIVY-389] [Minor] Pom updates

### PR DESCRIPTION
**Pull request by ajbozarth**
Updated pom.xml to match other Apache and Apache Incubator projects

### CODE REVIEW

**Comment by ajbozarth** [comment]
Had to remove parent section for now since it breaks the build, we should add it and address dependency issue in a future release.

**Comment by jerryshao** [comment]
LGTM, I was thinking to remove cdh related repos in pom file, since it is not used any more. I think we will push artifacts to maven or apache repo for the Apache release (still I'm not sure how to push artifacts to maven or apache repo 😄 ). What do you think?

**Comment by ajbozarth** [comment]
I left them in (just below the apache ones) because I noticed other incubator projects (incubator-streams for example) that did. I assume we can remove them eventually but I don't see a reason to without at least one release out. As for the release process I believe there was an email on the dev list recently with links about that.

**Comment by jerryshao** [comment]
I see, thanks!

**Comment by jerryshao** [comment]
Merging to master branch-0.4

**Pull request closed without merging**
