### PR TITLE
[LIVY-653][TESTS] scalatest 3.0.8

### PR DESCRIPTION
**Pull request by pjfanning**
## What changes were proposed in this pull request?

https://issues.apache.org/jira/browse/LIVY-653

Upgrading test jars.

## How was this patch tested?

unit tests run

Please review https://livy.incubator.apache.org/community/ before opening a pull request.

### CODE REVIEW

**Comment by jerryshao** [comment]
Hi @pjfanning thanks a lot for the contribution, may I know what's the purpose of this change?

**Comment by pjfanning** [comment]
@jerryshao I was thinking that updating scalatest would make it easier to support a scala 2.12 build -- and ultimately, a scala 2.13 build

**Comment by jerryshao** [comment]
I see. I would suggest to do Scala 2.12 support first, then we could upgrade the scalatest version.

**Comment by pjfanning** [comment]
@jerryshao one other reason to upgrade scalatest sooner rather than later is that v3.0.8 is maintained while v2 is not.

**Pull request closed without merging**
