### PR TITLE
Branch 0.2

### PR DESCRIPTION
**Pull request by zhaohaifei**
Who can tell me how to delete livy task in the starting state?

livy task has been in the starting state and can't be deleted. Can livy delete tasks in the starting state??

ece062a01485a87e8c269af5b96cba7c

### CODE REVIEW

**Comment by runzhiwang** [comment]
@zhaohaifei What is the response when you curl delete in starting state.

**Comment by runzhiwang** [comment]
@zhaohaifei Could you submit different PRs according to feature rather than one PR containing 9 commits.

**Comment by zhaohaifei** [comment]
> @zhaohaifei What is the response when you curl delete in starting state.

response:jar package can not be found.
ece062a01485a87e8c269af5b96cba7c

The program has been in starting state and does not terminate.

**Comment by zhaohaifei** [comment]
> Could you submit different PRs according to feature rather than one PR containing 9 commits.

Sorry, I am a newcomer, I don't know how to do it.

**Comment by zhaohaifei** [comment]
> > Could you submit different PRs according to feature rather than one PR containing 9 commits.
> 
> Sorry, I am a newcomer, I don't know how to do it.
   I originally wanted to leave a message, but I did not find issure.

**Comment by runzhiwang** [comment]
Do you want to merge your commits to apache/incubator-livy? If so, create one jira for each feature or bug, then submit one Pull Request for each jira.

**Comment by zhaohaifei** [comment]
> Do you want to merge your commits to apache/incubator-livy? If so, create one jira for each feature or bug, then submit one Pull Request for each jira.

no. I just want to leave a message.

**Comment by runzhiwang** [comment]
@zhaohaifei  If you want leave message or ask question, please email user@livy.incubator.apache.org. And you can close this Pull Request Now.

**Pull request closed without merging**
