### PR TITLE
[MINOR] Fix instructions on how to build Livy.

### PR DESCRIPTION
**Pull request by meisam**
## What changes were proposed in this pull request?
Update the README section with instructions on building Livy 

## How was this patch tested?
- Checked the rendered markdown.
- Executed the instructions.

## What remains to be done?
This instruction should be updated in the documentation each time Livy's repository name changes.

### CODE REVIEW

**Comment by mgaido91** [comment]
The change seems fine to me, have you checked that all the other part of the README are accurate? I think we should update if there are other imprecisions.

**Comment by meisam** [comment]
> have you checked that all the other part of the README are accurate?

I checked rest of the README file as well. I didn't see any other issue.

**Comment by mgaido91** [comment]
LGTM, if I won't see other comments in couple of days, I will merge this.

**Comment by mgaido91** [comment]
Thanks. Merging to master.

**Pull request merged**
