### PR TITLE
[LIVY-610][BUILD] optimization for windows environment build.

### PR DESCRIPTION
**Pull request by dockerzhang**
## What changes were proposed in this pull request?

we can remove requireOS restriction for windows building, and add execute permission for bin/livy-server.
https://issues.apache.org/jira/browse/LIVY-610
## How was this patch tested?
 tested manually.

### CODE REVIEW

**Comment by jerryshao** [comment]
Is above the only fix for window compiling?

**Comment by dockerzhang** [comment]
This patch is available for windows compiling and package, like "mvn clean -DskipTests -Pthriftserver package".  But unit tests and verify could not pass because of spark-submit command.

**Comment by jerryshao** [comment]
Another question, will the modification here change the behavior of *nix build?

**Comment by dockerzhang** [comment]
This patch applies to unix build without any loss, and built package works fine by test .

**Comment by jerryshao** [comment]
I'm OK with the current fix. But this is still a half-way fix for Windows build support. @dockerzhang would you please create follow-up jiras to track the left issues.

**Comment by jerryshao** [comment]
Merging to master branch.

**Comment by dockerzhang** [comment]
[LIVY-611](https://issues.apache.org/jira/projects/LIVY/issues/LIVY-611) is created to track the left issues.

**Pull request closed without merging**
