### PR TITLE
[LIVY-564] Support to check the spark batch job running progress

### PR DESCRIPTION
**Pull request by holmes-infra**
## What changes were proposed in this pull request?
When submitting a task,it's better to be able to view the batch job's progress
https://issues.apache.org/jira/browse/LIVY-564

(Please fill in changes proposed in this fix)
(Include a link to the associated JIRA and make sure to add a link to this pr on the JIRA as well)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review https://livy.incubator.apache.org/community/ before opening a pull request.

### CODE REVIEW

**Comment by vanzin** [comment]
What information exactly are you exposing here? The Spark code that updates the progress looks like this:

```
    updateResourceRequests()
    val progressIndicator = 0.1f
    val allocateResponse = amClient.allocate(progressIndicator)
```

As you can see, not very useful.

**Comment by vanzin** [comment]
I plan to close this and the bug if there's no reply to my question above.

**Comment by Tagar** [comment]
ping @holmes-infra 

thanks @vanzin

**Comment by vanzin** [comment]
Closing due to lack of response.

**Pull request closed without merging**
