### PR TITLE
[Minor] Add LICENSE and NOTICE files

### PR DESCRIPTION
**Pull request by ajbozarth**
Added Apache LICENSE and NOTICE files to the base directory of the repo.

This was split off of https://github.com/apache/incubator-livy/pull/21 for commit clarity

### CODE REVIEW

**Comment by ajbozarth** [comment]
@jerryshao we should probably get this merged sooner rather than later

**Comment by jerryshao** [comment]
Sure, I see.

**Comment by ajbozarth** [comment]
Ack, I just noticed that Livy isn't capitalized in the NOTICE file, is it possible to do an amend to fix that?

**Comment by jerryshao** [comment]
Maybe we can fix it later with other docs related PRs.

**Comment by ajbozarth** [comment]
I added the fix as a nit in the PR this spun off from

**Pull request closed without merging**
