### PR TITLE
LIVY-374. Update and unify all the license header to Apache

### PR DESCRIPTION
**Pull request by jerryshao**
This PR aims to update the license header of all the codes to Apache.

This is one task to move to Apache.

### CODE REVIEW

**Comment by jerryshao** [comment]
@zjffdu please help to review, thanks!

**Comment by jerryshao** [comment]
@zjffdu , do you any further comment, if not I'm going to merge this. The changes is quite straightforward.

**Comment by zjffdu** [comment]
LGTM @jerryshao  Go ahead.

**Comment by jerryshao** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
