### PR TITLE
[LIVY-694] Upgrade Jetty to 9.4.18.v20190429

### PR DESCRIPTION
**Pull request by peter-toth**
## What changes were proposed in this pull request?

Upgrade Jetty to 9.4.18.v20190429 to fix CVEs.

## How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by mgaido91** [comment]
thanks for the patch @peter-toth. I remember there were issues with the thrifserver part due to dependencies on hive which created issues with jetty versions different to the one used earlier. Have you checked that thriftserver works in http mode too with this patch?

**Comment by peter-toth** [comment]
Thanks for letting me know about that issue. I will check it with the updated Jetty version.

**Comment by coheigea** [comment]
This PR duplicates an existing PR: https://github.com/apache/incubator-livy/pull/175/files
@peter-toth is there any status on the Jetty check? It would be good to merge the fix due to the outstanding CVE issue.

**Comment by peter-toth** [comment]
@coheigea , unfortunately I didn't have time to check http mode, but we are using version 9.4.26.v20200117 now.

**Comment by coheigea** [comment]
This PR is superceded by https://github.com/apache/incubator-livy/pull/305

**Pull request closed without merging**
