### PR TITLE
[LIVY-384] [Docs] Added ability to build Livy Docs

### PR DESCRIPTION
**Pull request by ajbozarth**
[LIVY-384](https://issues.cloudera.org/browse/LIVY-384)

Included a minimized copy of the Livy website template files so we can use Jekyll to build the Livy Documentation.
I have also included a README that has instructions on how to build and deploy the Docs to the website.

Paired with apache/incubator-livy-website#7

### CODE REVIEW

**Comment by ajbozarth** [comment]
@lresende could you take a look at the files I took from the website and tell me if there are any more I don't need? I tried to only grab the necessary files, but there may still be some that don't need to be put in here.

**Comment by ajbozarth** [comment]
Forgot to deal with the rat check, I will fix this tomorrow

**Comment by ajbozarth** [comment]
Ended up just updating now. I removed an unused jQuery file, added apache headers to the css files and updated rat-excludes to ignore the generated Gemfile.lock and the JB and html template files.

**Comment by lresende** [comment]
If you are going to bring the actual layout to the source repository, you should properly update LICENSE/NOTICE files.

**Comment by ajbozarth** [comment]
@lresende what updates would be required?

**Comment by jerryshao** [comment]
@ajbozarth is it necessary to bring in this layout things?

**Comment by ajbozarth** [comment]
If we want to keep the Docs in the main repo and be able to build them for viewing then yes, this is also how Spark does it. But I did want @lresende to double check I didn't bring in any excess code, though I did spend a good chunk of time whittling down the necessary files from the website. If it's an issue, I can "rewrite" the website files so there are fewer of them, but that would just be combining files and reworking how the layout files are used compared to the website. I'd prefer to keep it as is though for compatibility with the website..

**Comment by ajbozarth** [comment]
If we'd rather not have the layout code in the main repo we can leave the Docs as markdown files and just copy them over to the website for each release, but then users wouldn't be able to build the Docs themselves like in Spark and other Apache projects.

**Comment by jerryshao** [comment]
OK, thanks for explanation. Can you please write a small `HOWTO` file for the steps to build docs, so that others can run it locally

**Comment by ajbozarth** [comment]
It's all in the README

**Comment by jerryshao** [comment]
Oh, thanks. I'm OK with the current solution.

**Comment by ajbozarth** [comment]
@lresende opinions?

**Comment by jerryshao** [comment]
any new update?

**Comment by ajbozarth** [comment]
Just waiting on the clarification on @lresende last comment

**Comment by lresende** [comment]
By adding the website "template" to main repository, this will be included as part of the source distribution and thus need to include any related libraries in the LICENSE/NOTICE. I would just check the template repository for what is there and remove any piece that you might have removed from the current code. 

https://github.com/apache/apache-website-template/blob/master/LICENSE

**Comment by ajbozarth** [comment]
I've updated LICENSE appropriately, including some from the Web UI as well. @lresende can you double check `LICENSE` looks good?

**Comment by jerryshao** [comment]
@lresende we're waiting for your review, can you please help to review and give us a green light? Thanks!

@ajbozarth can you please retrigger the test.

**Comment by lresende** [comment]
The license additions LGTM

**Comment by jerryshao** [comment]
Thanks @ajbozarth and @lresende , I will merge to master and branch 0.4.

**Pull request closed without merging**
