### PR TITLE
LIVY-886: Make livy compatible with python 3.8+

### PR DESCRIPTION
**Pull request by prongs**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)
(Include a link to the associated JIRA and make sure to add a link to this pr on the JIRA as well)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review https://livy.incubator.apache.org/community/ before opening a pull request.

### CODE REVIEW

**Comment by gabrielmagno** [comment]
This PR is duplicated with #314

**Comment by prongs** [comment]
Yes @gabrielmagno both solutions should work. Problem is, livy is an un-maintained project by now. 

* Last commit in maste was more than a year ago. 
* Livy hasn't been released after adding support for spark-3/scala-2.12

**Comment by uberadam2392** [comment]
Hi @prongs and @gabrielmagno is there any solution to this that can be patched on the user end?

**Comment by leesf** [comment]
just merge another one. https://github.com/apache/incubator-livy/pull/314. Closing this one.

**Pull request closed without merging**
