### PR TITLE
[Minor] Adding a PR Template

### PR DESCRIPTION
**Pull request by ajbozarth**
Added a pull request template like Spark's to help new Livy devs

### CODE REVIEW

**Comment by ajbozarth** [comment]
@jerryshao do you think this would be useful? If it looks good to you I'll use this to test my new committer privileges.

**Comment by jerryshao** [comment]
Yes, it looks good to me. Sorry for late response, I was off last week.

**Comment by jerryshao** [comment]
I think you need to add this file to rat exclude.

**Comment by ajbozarth** [comment]
I noticed you were off sometime around Thursday >.< and I'll add the rat exclude then push this after it passes tests

**Pull request closed without merging**
