### PR TITLE
fixing the Livy local file upload

### PR DESCRIPTION
**Pull request by firemonk9**
https://groups.google.com/a/cloudera.org/forum/#!topic/livy-user/mm-XEhANDHU

(Please fill in changes proposed in this fix)
Iinclude a link to the associated JIRA and make sure to add a link to this pr on the JIRA as well)

The patch is tested manually.

### CODE REVIEW

**Comment by vanzin** [comment]
Hi @firemonk9 , you opened the same PR earlier. This is not a fix. If you're trying to ask a question, please use the mailing lists. Could you close this PR (and the other)?

**Comment by firemonk9** [comment]
Hello Marcelo,

         I am having the same problem as for the folks in this link (
https://groups.google.com/a/cloudera.org/forum/#!topic/livy-user/mm-XEhANDHU)
and I had made the fix. It is just one line code change

https://github.com/apache/incubator-livy/pull/115/commits/7cfde5a356121df7064f507b058bc25629c786b4

I am having to make my own build just for this small fix. (I am testing
with the fix for last two months.)

Firemonk9

**Comment by vanzin** [comment]
In that case can you follow the contribution guide? 
http://livy.incubator.apache.org/community/

Basically:
- file a bug with the information
- explain the fix in the PR
- add tests

Also please close your other PR (#106).

**Comment by vanzin** [comment]
Closing for now. Update the PR to follow the contribution guidelines and then re-open.

**Pull request closed without merging**
