### PR TITLE
[LIVY-693] Upgrade jackson to 2.9.10

### PR DESCRIPTION
**Pull request by peter-toth**
## What changes were proposed in this pull request?

Upgrade Jackson to 2.9.10 which fixes many CVEs: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.10

## How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by peter-toth** [comment]
recheck this please

**Comment by peter-toth** [comment]
retest this please

**Comment by jerryshao** [comment]
Please reopen the PR or push an empty commit to trigger travis.

**Comment by jerryshao** [comment]
Yes, it is super weird, I've never met this issue before, can you reproduce it locally?

**Comment by peter-toth** [comment]
No issues locally.
I'm not familiar with this build process, but it looks like there is some issue with `/home/travis/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar` in maven cache. Can you remove it?

**Comment by jerryshao** [comment]
I guess we cannot delete the maven cache, it is the behavior of Travis. I was thinking it might not be the environment issue, would you please take a deep look?

**Comment by peter-toth** [comment]
I think this is a maven cache issue on that particular machine. Only 1 job is failing with this build issue, the `Spark 2.2 Unit Tests`. Other jobs, including the `Spark 2.2 ITs` are ok and it has no issue with `scala-maven-plugin:3.2.2:compile (scala-compile-first) @ livy-api` phase.

**Comment by coheigea** [comment]
@peter-toth I think this PR and associated JIRA should be closed, as it is superceded by the upgrade to 2.10.1 (https://github.com/apache/incubator-livy/pull/258/files) which fixes many recent CVEs in Jackson Databind.

**Comment by jerryshao** [comment]
Upgraded to 2.10.1, thanks a lot for the contribution.

**Pull request closed without merging**
