### PR TITLE
[LIVY-878] Replace log4j with reload4j

### PR DESCRIPTION
**Pull request by dacort**
## What changes were proposed in this pull request?

- Replace log4j with reload4j
- Add exclusions for transitive log4j dependencies including `spark-core`, `hadoop-common` (and others), `zookeeper`, and `apacheds-server`.
- https://issues.apache.org/jira/browse/LIVY-878

## How was this patch tested?

- unit/integration tests

### CODE REVIEW

**Review by ksumit — COMMENTED** [review]
I noticed following in `mvn dependency:tree` output, the scope is test, so not that worrisome, but thought to bring to your attention.
```
[INFO] +- org.apache.directory.server:apacheds-server-integ:jar:2.0.0.AM26:test
[INFO] |  +- org.apache.directory.server:apacheds-core-annotations:jar:2.0.0.AM26:test
[INFO] |  |  +- org.apache.directory.mavibot:mavibot:jar:1.0.0-M8:test
[INFO] |  |  \- org.apache.directory.server:apacheds-mavibot-partition:jar:2.0.0.AM26:test
[INFO] |  +- org.apache.directory.server:apacheds-core-jndi:jar:2.0.0.AM26:test
[INFO] |  +- org.apache.directory.server:apacheds-interceptor-kerberos:jar:2.0.0.AM26:test
[INFO] |  +- org.apache.directory.server:apacheds-server-annotations:jar:2.0.0.AM26:test
[INFO] |  |  \- org.apache.directory.server:apacheds-protocol-kerberos:jar:2.0.0.AM26:test
[INFO] |  +- org.apache.directory.server:apacheds-test-framework:jar:2.0.0.AM26:test
[INFO] |  |  \- org.apache.directory.api:api-ldap-codec-standalone:jar:2.0.0:test
[INFO] |  |     \- org.apache.directory.api:api-ldap-net-mina:jar:2.0.0:test
[INFO] |  +- ldapsdk:ldapsdk:jar:4.1:test
[INFO] |  +- log4j:log4j:jar:1.2.17:test
```

**Comment by ayushtkn** [comment]
If it isn't getting used, its better if we could exclude the log4j dependency completely even from test scope

**Comment by dacort** [comment]
AhI thought I addressed the `apacheds-server-integ` - will double-check that.

**Review by lmccay — APPROVED** [review]
+1

**Comment by dacort** [comment]
Will trigger CI with a push today.

**Comment by dacort** [comment]
Bummer, CI failed. Will take a look either later today or Monday.

**Comment by dacort** [comment]
Integration tests are working, but unit tests still failing with, what I think is an error related to slf4j/log4j loading.

```
[INFO] Running org.apache.livy.thriftserver.session.ColumnBufferTest
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.572 s <<< FAILURE! - in org.apache.livy.thriftserver.session.ColumnBufferTest
[ERROR] testColumnBuffer(org.apache.livy.thriftserver.session.ColumnBufferTest)  Time elapsed: 2.147 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/log4j/Level
        at org.apache.livy.thriftserver.session.ColumnBufferTest.testColumnBuffer(ColumnBufferTest.java:53)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
        at org.apache.livy.thriftserver.session.ColumnBufferTest.testColumnBuffer(ColumnBufferTest.java:53)

[INFO] Running org.apache.livy.thriftserver.session.ThriftSessionTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.024 s <<< FAILURE! - in org.apache.livy.thriftserver.session.ThriftSessionTest
[ERROR] org.apache.livy.thriftserver.session.ThriftSessionTest  Time elapsed: 0.024 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.apache.livy.thriftserver.session.ThriftSessionTest.setUp(ThriftSessionTest.java:60)
Caused by: java.lang.IllegalStateException: org.slf4j.LoggerFactory in failed state. Original exception was thrown EARLIER. See also http://www.slf4j.org/codes.html#unsuccessfulInit
        at org.apache.livy.thriftserver.session.ThriftSessionTest.setUp(ThriftSessionTest.java:60)
```

**Comment by dacort** [comment]
Fixed the `java.lang.NoClassDefFoundError` error with additional exclusions. 

Unit tests are failing, however I think it's due to a flaky test based on behavior observed in CI where unit tests pass on the PR but fail once merged into master and vice-cersa.

There's an old [mailing list thread](https://www.mail-archive.com/dev@livy.incubator.apache.org/msg00794.html) that also discusses the issue, but with no resolution.

```
The second error, TestSparkClient.testJobSubmission, is random. I see the
failure ~25% of the times. As it turned out, the Echo job was returning,
sometimes, even before we added the listener on the job handle. So the
listener.onJobStarted method is not invoked. This can be fixed in multiple
ways but I updated the Echo job, which used to simply return its attribute
value, to do what ScalaEcho job is doing. So the Echo job now returns
"jc.sc().parallelize(list,
1).collect().get(0);". Even this could still be fast enough to cause the
same error. However I couldn't reproduce it again. Also the updated code is
taking ~1 sec or more on spark's side. So hopefully this should be ok.
```

**Comment by gyogal** [comment]
Interesting, this test does seem to be flaky. The recent post-commit tests have succeeded, but that may be just pure luck. Could you please retrigger the tests on this one? If this test proves to be flaky, we should file a separate JIRA for it. Also, thanks for finding that old email thread about this test!

**Comment by dacort** [comment]
Might have figured this out! Swapping `slf4j-api` with `slf4j-reload4j` seems to get me past `TestSparkClient`. Running the full suite now.

**Comment by lmccay** [comment]
@dacort - looks like the same failures?

**Comment by dacort** [comment]
@lmccay Yes but I've got another working branch over here https://github.com/apache/incubator-livy/tree/fix/log4j-reload4j-part2 that appears to be working. Just need to verify everything looks good.

**Comment by lmccay** [comment]
@dacort - curious where you are with the separate branch and plan here?

**Comment by dacort** [comment]
@lmccay @ksumit OK! I've merged in changes from my working branch. Tests are green! (After some manual retries...)

Could y'all take one more glance at this and the I think it's good to merge in. Apologies this has taken so long, appreciate your patience and follow ups. 🙏

**Review by lmccay — APPROVED** [review]
LGTM!

+1

**Review by ksumit — COMMENTED** [review]
I see we are keeping slf4j-reload4j as provided dependency, that means, it won't be bundled in the release, is that ok? how would this be available at runtime? can we please do a check on the release tarball if this jar magically appears or not?

**Comment by dacort** [comment]
> slf4j-reload4j as provided dependency

I'll check, but it is defined as a non-provided dependency in the main `pom.xml`.

**Review by ksumit — APPROVED** [review]

**Pull request merged**
