### PR TITLE
[MINOR] Update version of ffi.

### PR DESCRIPTION
**Pull request by vanzin**
The other updates were made when building the docs, more exactly when
trying to fix "bundle install", since things wouldn't build with the
existing dependencies.

### CODE REVIEW

**Comment by vanzin** [comment]
@ajbozarth since you made these kinds of changes before; not sure whether the non-ffi changes are needed, but it's the only way they would build.

**Comment by vanzin** [comment]
There's a more recent version, let me try to update to that one instead.

**Comment by ajbozarth** [comment]
As long as you've tested building the docs I'll trust you it good

**Comment by vanzin** [comment]
They build fine and clicking around looked ok. I just don't know what all this stuff is actually used for...

**Comment by ajbozarth** [comment]
Crazy enough, everything in the `Gemfile.lock` is part of the dependency tree of the few actual dependancies in the `Gemfile`

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
