### PR TITLE
[LIVY-795] Add support for PySpark with Python >= 3.8 

### PR DESCRIPTION
**Pull request by gabrielmagno**
## What changes were proposed in this pull request?

A mock for the `ast.Module` is created in case of running older Python versions (< 3.8). The mocked module will ignore the new `type_ignores` parameter, and pass only the first parameter to the old module.

As already mentioned by Shiquan Wang (the issue reporter), Python 3.8 introduced a change in the API (https://github.com/python/cpython/pull/11645/files), and IPython had a similar problem. The strategy used for this fix is similar to the one utilized by IPython in this PR: https://github.com/ipython/ipython/pull/11593 

JIRA: https://issues.apache.org/jira/projects/LIVY/issues/LIVY-795

## How was this patch tested?

Tested locally, using Jupyter notebook to run pyspark commands.

### CODE REVIEW

**Comment by gabrielmagno** [comment]
The build for `Spark 3.0 Unit Tests` failed, but so does the master branch. Probably not related to the Python fix.

**Comment by siege089** [comment]
It appears master tests are passing, any chance this build could be rechecked and merged? Would love to be able to run multiple lines of python at once in 3.8.

**Comment by gabrielmagno** [comment]
@siege089 would be glad to do so, but [latest master commit](https://github.com/apache/incubator-livy/commit/4d8a912699683b973eee76d4e91447d769a0cb0d) is from Aug 2020, and it was already incorporated in my branch when I made the pull request. It has a ["failed" build status](https://travis-ci.org/github/apache/incubator-livy/builds/718090124).

**Comment by dacort** [comment]
*bump* Any chance we can revive this?

**Comment by gabrielmagno** [comment]
> @siege089 would be glad to do so, but [latest master commit](https://github.com/apache/incubator-livy/commit/4d8a912699683b973eee76d4e91447d769a0cb0d) is from Aug 2020, and it was already incorporated in my branch when I made the pull request. It has a ["failed" build status](https://travis-ci.org/github/apache/incubator-livy/builds/718090124).

@dacort Unfortunately I'm still limited to the master's fail commit from August 2020. If there is anything I could do to circumvent it in the meantime, I would be glad to do it.

**Comment by dacort** [comment]
@gabrielmagno Thanks for the reply! Let me see if I can clone the change and open a new PR.

**Comment by mgaido91** [comment]
I am more familiar with the thriftserver part, so I am not confident reviewing this PR, btw the CI is failing, so a first step would be having the CI working fine.

**Comment by mgaido91** [comment]
Then I would recommend fixing the tests on the master branch and then go ahead. It is the safest option IMHO.

**Comment by gabrielmagno** [comment]
> Then I would recommend fixing the tests on the master branch and then go ahead. It is the safest option IMHO.

I agree with you, thank you for the feedback!

I would be glad to do it, but this is out of my expertise and knowledge of the project :-(

**Comment by derache123** [comment]
Any update on this PR? Is anyone still looking at this?

**Comment by virginiayung** [comment]
Hi, can we get some help here on pushing this forward? We are also blocked by not being able to use Python 3.8 because of this issue. Thanks!

**Comment by derache123** [comment]
Bump. This seems like a crucial issue to fix and I'm honestly quite surprised that it's been sitting for so long.

**Comment by gabrielmagno** [comment]
Yes, it is so sad that the build of the main branch is broken for almost 2 years 😢

**Comment by uberadam2392** [comment]
Hi I ran into this issue recently, where if I run my code as follows in separate cells line-by-line, there is no error:

```
import scipy
```

```
print(scipy.__version__)
```

```
import IPython
```

But as soon as I put them into the same Jupyter cell:

```
import scipy
import IPython
print(scipy.__version__)
```

I get the following error:

```
required field "type_ignores" missing from Module
Traceback (most recent call last):
  File "/tmp/362488836129912165", line 215, in execute
    code = compile(mod, self.cell_name, 'exec')
TypeError: required field "type_ignores" missing from Module
```

See attached screenshot.

Screen Shot 2022-09-30 at 10 28 19 AM

Is there anyway to fix this on the user end? I have a SparkMagic / PySpark cluster provisioned for me, and Idk how long a hack fix would take upstream...

**Comment by uberadam2392** [comment]
Does anyone know an easy workaround if I need to use Python3.8+, Jupyter notebook, PySpark (3.0+ to support Python3.8)?

Thanks!

**Comment by gabrielmagno** [comment]
Hi @uberadam2392. 

You could try using my personal fork of livy: https://github.com/gabrielmagno/incubator-livy .
In the README there is a section `Building Livy` which you can follow to build locally.

Alternatevely, you could try applying the patch by yourself, you have to change a single file.
Look at the commit with the change: https://github.com/gabrielmagno/incubator-livy/commit/81a4e92b5abbc65f27b35454a8f28a72b8f4179b

**Comment by aabdullah-getguru** [comment]
> Bump. This seems like a crucial issue to fix and I'm honestly quite surprised that it's been sitting for so long.

Well, it is what it is :), I'm surprised too, but the contributors are doing this on their own free time, so have to be patient :).

**Comment by dacort** [comment]
It looks like the project is being reinstated!! @gabrielmagno looks like there are some new commits including a fix for CI. 

While I don't think the team is pulling in old PRs quite yet (based on mailing list chatter), might be good to rebase this on master if you have the chance!

**Comment by lmccay** [comment]
> It looks like the project is being reinstated!! @gabrielmagno looks like there are some new commits including a fix for CI.
> 
> While I don't think the team is pulling in old PRs quite yet (based on mailing list chatter), might be good to rebase this on master if you have the chance!

We can consider PRs with active representation for the first release. Just don't want to chase folks down and hold things up when we can just turn the crank and get a clean release out as a first goal.

**Comment by dacort** [comment]
Awesome thanks @lmccay !

**Comment by gabrielmagno** [comment]
@dacort (cc @lmccay)

It is building properly now! 🥳 

I believe this PR has passed all the checks and is ready to be merged upstream, as soon as the core developers see as appropriate and have the time to look into it 🙂

Just as a "pitch" for merging this PR (for any core developer looking into this): this is a relatively simple PR that modifies a single Python file, and does not even modify the main core Scala code of the project. On the other hand, I think it is very important because Python 3.7 will reach end-of-life in just a couple of months ([2023-06-27](https://devguide.python.org/versions/)), so making livy compatible with Python 3.8+ seems to be a nice goal to have.

**Review by leesf — APPROVED** [review]
LGTM, @gabrielmagno Thanks for your patience.

**Pull request merged**
